# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: robot_kol
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - JKL1
    - JKL2
    - JKL3
    - JKL4
    - JKL5
    - JKL5_dummy_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
robot_kol_controller:
  type: position_controllers/JointPositionController
  joints:
    - JKL1
    - JKL2
    - JKL3
    - JKL4
    - JKL5
  gains:
    JKL1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    JKL2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    JKL3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    JKL4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    JKL5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1